repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: check-executables-have-shebangs
  - id: check-json
  - id: check-merge-conflict
  - id: check-shebang-scripts-are-executable
  - id: check-toml
  - id: check-yaml
  - id: double-quote-string-fixer
  - id: end-of-file-fixer
  - id: mixed-line-ending
    args: ['--fix=lf']
  - id: requirements-txt-fixer
  - id: trailing-whitespace
- repo: https://github.com/myint/docformatter
  rev: v1.4
  hooks:
  - id: docformatter
    args: ['--in-place']
- repo: https://github.com/pycqa/isort
  rev: 5.8.0
  hooks:
    - id: isort
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.812
  hooks:
    - id: mypy
      args: ['--ignore-missing-imports']
- repo: https://github.com/pre-commit/mirrors-yapf
  rev: v0.31.0
  hooks:
  - id: yapf
    args: ['--parallel', '--in-place', '--style={spaces_before_comment: 2}']
