version: "3.8"
services:
  train:
    image: pl_gaze_estimation
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        PYTHON_VERSION: ${PYTHON_VERSION:-3.9.9}
    environment:
      TORCH_HOME: /.torch
    tty: true
    volumes:
      - ${PWD}:/work
      - ${TORCH_HOME}:/.torch
      - ${HOME}/.netrc:/.netrc
      - ${HOME}/.config:/.config
    working_dir: /work
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: ["gpu"]
