version: "2.3"
services:
  train:
    image: pl_gaze_estimation
    runtime: nvidia
    ipc: host
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        PYTHON_VERSION: ${PYTHON_VERSION:-3.9.6}
    environment:
      TORCH_HOME: /.torch
    tty: true
    volumes:
      - ${PWD}:/work
      - ${TORCH_HOME}:/.torch
      - ${HOME}/.netrc:/.netrc
      - ${HOME}/.config:/.config
    working_dir: /work
